# Cargo.toml
[package]
name = "credential_encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
ldap3 = { version = "0.11", features = ["tls"] }
native-tls = "0.2"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }


